### PR TITLE
Revert "Created DAC Driver Library"

### PR DESCRIPTION
**Pull request by jaypacamarra**
Reverts DAQSimple/DSX_fw#9

@manraj-s , lol after merging your DAC branch, I can't seem to see the header file for my source files anymore. For ex. I created encoder.c and I try 
```C
#include encoder.h
```
and encoder.h says can't be found. Can you please try on your system if its the same?

### CODE REVIEW

**Comment by jaypacamarra** [comment]
I went back to this commit **fd8653efc0bfe1da33e9a7ddf6fe2e7ef961844f**
and I was able to create a new library and include the header file in the source file. That's so weird, something happened when I merged DAC into develop, I'm not sure what and made it so you cant create anymore libraries.

**Comment by jaypacamarra** [comment]
Merging a branch to develop will probably have to be done in two ways:

1. merge develop into your feature branch and test if anything broke. If nothing broke then do a pull request.
2. Or, Pull request and commit only the main.c and driver folder and nothing else and take pictures of the .ioc file for how your driver peripherals are set up. We'll take those ioc configurations and do them manually in the develop branch.

**Comment by manraj-s** [comment]
So I merged develop into the DAC2 branch and it was already up to date.

**Comment by jaypacamarra** [comment]
So you did git merge develop from your branch and there was no conflicts?

**Comment by manraj-s** [comment]
Yeah

**Comment by jaypacamarra** [comment]
Huh. Okay I'm not sure what happened then. I feel like we need to merge with the second method where you only send main.c and your driver folder to merge into develop.

**Comment by manraj-s** [comment]
I think it would be easier if I created a new branch.

**Review by manraj-s — APPROVED** [review]
I'll create a pull request with only the DAC folder.

**Pull request merged**
