### PR TITLE
4 Channel - DMA - 2xOversampling - ADC Configuration and Library

### PR DESCRIPTION
**Pull request by tsaxon**
This setup is serially reading each of the four channels every 47.5*2 clock cycles. 

Once the ADC is started using Start_ADC(), the ADC will be constantly writing the four ADC channels to adc_buf in a circular configuration, refreshing the buffer when new values are converted.

### CODE REVIEW

**Review by jaypacamarra — CHANGES_REQUESTED** [review]
This ADC driver looking good!

If I could have you clean up your adc.h and adc.c by removing anything unnecessary that would be great. I've tested your code and works as expected with the over sampled readings for the 4 channels. Just clean up main and remove the test code and you should be good to merge after doing those things.

**Review by manraj-s — COMMENTED** [review]
I agree with Jay. I think also moving the adc_buff array to the header file would also be good.

**Comment by tsaxon** [comment]
Cleaned everything up and have included adc_buf in adc.h as well. I don't need to make another pull request right?

**Comment by jaypacamarra** [comment]
Ok great. I'll test this merge first before actually accepting this pull request. Give me a day.

**Comment by jaypacamarra** [comment]
No you dont need to pull request again. Once you make a pull request, any additional commits to your branch will be included automatically in the pull request.

**Pull request merged**
