### PR TITLE
Encoder Library

### PR DESCRIPTION
**Pull request by manraj-s**
- Timer 4 is setup in encoder mode using pins PA11 (Channel A) and PA12 (Channel B). 
- Timer 7 is setup to interrupt at 4Hz and calculate rpm and frequency. 
- The user can specify the counts per revolution (CPR) which has a max of 65535. 
- The encoder count can range from -32767 to 32767. 

*Note that the limit for frequency which the encoder can read is 64kHz.*

The CPR should be set first, using the following function, before starting the encoder 
```C
Encoder_Set_CPR(uint16_t CPR_set);
``` 
After setting the CPR the encoder is started using the following function
```C
Encoder_Start(void);
``` 
Frequency, rpm, and count be read using the following functions.
```C
Encoder_Read_Count(void);
Encoder_Read_Freq(void);
Encoder_Read_RPM(void);
```

### CODE REVIEW

**Comment by jaypacamarra** [comment]
Nice job, I'll take a look within a day. Also good idea with explaining how to actually use the driver library functions!

**Comment by jaypacamarra** [comment]
Oh @manraj-s , we forgot to add a function for the encoder that determines the direction. So clockwise or counter clockwise rotation. If you could add that, then this library is done. The output should be 1 or 0.

**Comment by manraj-s** [comment]
Can we remove the absolute value of the encoder count when calculating the rpm and frequency to have direction

**Comment by jaypacamarra** [comment]
Although that could work, you may face issues of noisy readings when the encoder count resets to 0. The more common approach is to read the other encoder channel's voltage level at each rising edge **or** falling edge of timer 4. But just remember, that for some reason even though you set timer 4 to interrupt every rising edge, it actually interrupts at the rising and falling edge. 
image

**Comment by manraj-s** [comment]
Direction of the encoder is returned using the following function.
```C
Encoder_Get_DIR(void);
``` 
*Note:*
- 0 is counting up
- 1 is counting down

**Comment by jaypacamarra** [comment]
Alright I tested the Encoder_Get_DIR(void); and it works.

Though when testing it, I noticed you didn't include the 
``` C
Encoder_Start();
```
in main.c. Is this intentional? Shouldnt we load a default CPR and call the Encoder Start function just above the while (1)? Or do you want to only start the encoder when an Encoder read command is triggered from Simulink?

**Comment by manraj-s** [comment]
I wasn't sure on how we're setting up main.c so I left it out. Are we starting every command at the beginning at a default state or are we waiting for a Simulink trigger to start the specified command?

**Comment by jaypacamarra** [comment]
These can be initialized at a default state such as the dsx data structure, serial, adc, dac, safety, and Encoder. It's okay to have Encoder start before the while(1) in main.

**Comment by manraj-s** [comment]
Started encoder in main.c with default CPR of 100. Also changed the ```Encoder_Set_CPR``` function to set the CPR to the default if input is 0.

**Review by jaypacamarra — APPROVED** [review]
Ready to merge. Good job. LGTM.

**Pull request merged**
